

services:
  superset_db:
    image: postgres:12
    container_name: superset_db
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: superset
    ports:
      - "5432:5432"
    volumes:
      - superset_db_data:/var/lib/postgresql/data
    networks:
      - big-data-network
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 5
      test: [ "CMD-SHELL", "pg_isready -U superset" ]

  superset:
    build:
      context: ${BUILD_CONTEXT}
    container_name: superset
    environment:
      SUPERSET_ENV: development
      SUPERSET_DATABASE_URI: postgresql://superset:superset@superset_db:5432/superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: superset
      SUPERSET_CONFIG_PATH: /app/pythonpath/superset_config.py
      SUPERSET_LOAD_EXAMPLES: yes
    ports:
      - "9088:9088"
    volumes:
      - ${APP_DATA_DIR}/volumes/superset_home:/app/superset_home
      - ${CONFIGS_DIR}/superset_config.py:/app/pythonpath/superset_config.py
    networks:
      - big-data-network
    depends_on:
      superset_db:
        condition: service_healthy
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 5
      test: [ "CMD-SHELL", "curl -f http://localhost:9088/health || exit 1" ]
    command: ["/bin/bash"]
networks:
  big-data-network:
    external: true
volumes:
  superset_db_data:
  superset_home:
